import { CardDefinition, CardType } from './types';

export const CARD_DEFINITIONS: Record<string, CardDefinition> = {
  blood_well: {
    id: 'blood_well',
    name: '血泉',
    type: CardType.CONTINUOUS,
    costMinerals: 4,
    costTech: 1,
    description: '持续卡：打出后，每 5 秒为己方主星球恢复 5 点生命值。',
    techStage: 2,
  },
  loaded_dice: {
    id: 'loaded_dice',
    name: '灌铅骰子',
    type: CardType.CONTINUOUS,
    costMinerals: 5,
    costTech: 0,
    description: '持续卡：打出后，每 5 秒额外获得 2 点矿物。',
    techStage: 1,
  },
  build_scout: {
    id: 'build_scout',
    name: '建造探索船',
    type: CardType.INSTANT,
    costMinerals: 3,
    costTech: 0,
    description: '立即建造一艘探索船，自动部署在主星球。可派往任何星球进行占领或采矿。',
    techStage: 1,
  },
  build_frigate: {
    id: 'build_frigate',
    name: '建造护卫舰',
    type: CardType.INSTANT,
    costMinerals: 5,
    costTech: 0,
    description: '立即建造一艘护卫舰，自动部署在主星球。不可移动，自动拦截入侵的敌舰。',
    techStage: 2,
  },
  build_dreadnought: {
    id: 'build_dreadnought',
    name: '建造主力舰',
    type: CardType.INSTANT,
    costMinerals: 10,
    costTech: 0,
    description: '立即建造一艘主力战舰，部署在主星球。拥有强大火力和护盾，可进行战斗与占领。',
    techStage: 3,
  },
  spy: {
    id: 'spy',
    name: '间谍',
    type: CardType.INSTANT,
    costMinerals: 4,
    costTech: 0,
    description: '派遣一艘隐形间谍船。派往敌方或中立星球可混入并伪装。使敌方每 5 秒失去 2 矿物，己方获得 1 矿物。',
    techStage: 2,
  },
  blood_sacrifice: {
    id: 'blood_sacrifice',
    name: '血祭',
    type: CardType.INSTANT,
    costMinerals: 0,
    costTech: 0,
    description: '法术卡：消耗己方主星球 25 点生命值，立刻换取 15 点晶体矿。主星球生命低于 26 时无法使用。',
    techStage: 2,
  },
  purge: {
    id: 'purge',
    name: '大清洗',
    type: CardType.INSTANT,
    costMinerals: 3,
    costTech: 1,
    description: '法术卡：对己方某个星球执行大清洗，立刻清除该星球上的所有敌方间谍船（包括伪装的间谍）和 Debuff。',
    techStage: 3,
  },
  armed_citizenry: {
    id: 'armed_citizenry',
    name: '全民皆兵',
    type: CardType.ABILITY,
    costMinerals: 0,
    costTech: 0,
    description: '能力卡：位于手牌时，使你所有建造飞船的矿物消耗 -1，最低为 0。不消耗该卡。',
    techStage: 1,
  },
};

export const DECK_POOL = [
  'blood_well',
  'loaded_dice',
  'build_scout',
  'build_scout',
  'build_frigate',
  'build_frigate',
  'build_dreadnought',
  'build_dreadnought',
  'spy',
  'spy',
  'blood_sacrifice',
  'purge',
  'armed_citizenry',
  'armed_citizenry',
];
